# Generated by Django 4.2.30 on 2026-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_lead_and_sketchfab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accent_color',
            field=models.CharField(default='#c42e28', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='sketchfab_id',
            field=models.CharField(blank=True, help_text='Sketchfab model ID (e.g. 70ab4f4164b54afbad87f174f8b285c1)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='sketchfab_title',
            field=models.CharField(blank=True, help_text='Display name for the 3D model', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=300),
        ),
    ]
